config/routes.rb
Rails.application.routes.draw do


	require 'resque/server'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'posts', to: 'posts#index'

  # get 'posts/new', to: 'posts#new'

  post 'posts/create', to: 'posts#create', as: :posts_new

  delete 'posts/delete/:id', to: 'posts#destroy', as: :post_delete

  root 'posts#index'

  post 'comments/create', to: 'comments#create', as: :comments_create

  post 'images/create', to: 'images#create', as: :images

  mount Resque::Server.new, at: "/resque"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

	belongs_to :post
	belongs_to :user
end

app/models/image.rb
class Image < ApplicationRecord
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
 validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

	belongs_to :post


end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments
	has_many :images
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :posts
         has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create

		@comment = Comment.create(content: params[:comment][:content], post_id: params[:comment][:post_id], user_id: current_user.id)
		redirect_to root_path


		# UserMailer.new_comment(@comment.id).deliver_now

		Resque.enqueue(NewCommentEmail, @comment.id)
	end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

	def create

		image = Image.create(avatar: params[:image][:avatar], post_id: params[:image][:post_id])
		redirect_to root_path

	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index

		@posts = Post.all
		@post = Post.new

		@comment = Comment.new
		@image = Image.new
		@images = Image.all
	end

	def create

		post = Post.create(title: params[:post][:title], content: params[:post][:content], user_id: current_user.id)
		redirect_to root_path

	end
	
	def destroy
		@post = Post.find_by(params[:id])
		@post.destroy

		redirect_to root_path
							
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelloTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div>
  		<% if user_signed_in? %>
  			<p><%= current_user.email %></p>
  			<p><%= link_to 'Sign-out', destroy_user_session_path, method: :delete %>
  		
  		<% else %>
  			<p><%= link_to 'Sign-in', new_user_session_path %></p>
  			<p><%= link_to 'Sign-up', new_user_registration_path %></p>
  		<% end %>


    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<br>

<p> Create Post </p>
<div>
	<%= form_for @post, url: posts_new_path do |p| %>
		<%= p.label :title %>
		<%= p.text_area :title %>
		<br>
		<%= p.label :content %>
		<%= p.text_area :content %>
		<br>
		<%= p.submit %>			

		
	<% end %>


</div>

<p> Posts are</p>


<div>
	<% @posts.each do |post| %>
		Title----<%= post.title %>
		<br>
		Content----<%= post.content %>
		<%= link_to "Delete ", post_delete_path(post.id), method: :delete %>
		<br>
			<div>
				<p> CREATE COMMENT </p>
					<div>
				<%= form_for @comment, url: comments_create_path do |c| %>
					<%= c.hidden_field :post_id, value: post.id%>
					<%= c.label :Content%>
					<%= c.text_area :content%>
					<%= c.submit %>
				<% end %>
								<p>--------Comments are</p>

					</div>
					<% post.comments.each do |comment| %>
						<p>..<%= comment.content%></p>
					<% end %>
			</div>
			<div>

				<p> CREATE IMAGES </p>
					<div>
						
						<%= form_for @image, url: images_path do |i| %>
						<%= i.label :Image %>
						<%= i.file_field :avatar %>
						<%= i.hidden_field :post_id, value: post.id %>
						<%= i.submit %>
						<% end %>

					</div>
			</div>

			<div>
				<% post.images.each do |image| %>
				<%= image_tag image.avatar.url, id:"image-style" %>
				<% end %>
			</div>
			
	<% end %>
	
</div>




<div>


</div>